export const COURSE_DETAILS = [
  {
    slug: 'data-analyst-with-genai',
    icon: '📊',
    title: 'Data Analyst with GenAI',
    color: 'from-blue-500/20 to-cyan-500/10',
    accent: 'gh-blue',
    image: '/data_analyst_card_1781095293922.png',
    tagline: 'Turn raw data into business insights with Python, SQL & GenAI.',
    shortDesc: 'Learn analytics, dashboards, and AI-assisted reporting for MNC roles.',
    duration: '4–5 Months',
    level: 'Beginner Friendly',
    mode: 'Classroom · KPHB, Hyderabad',
    description:
      'This program trains you from zero to job-ready Data Analyst with hands-on Python, SQL, Excel, Power BI, and Generative AI tools. You will work on real datasets, build dashboards, automate reports with LLMs, and prepare for analyst interviews at top IT companies.',
    modules: [
      'Python fundamentals for data analysis',
      'SQL & relational databases',
      'Excel, statistics & data cleaning',
      'Power BI / visualization dashboards',
      'GenAI for report automation & insights',
      'Capstone analytics project + portfolio',
    ],
    skills: ['Python', 'SQL', 'Power BI', 'Data Cleaning', 'LLM Prompting', 'Business Reporting'],
    tools: ['Python', 'Pandas', 'MySQL', 'Excel', 'Power BI', 'ChatGPT / Copilot'],
    outcomes: [
      'Build end-to-end analytics projects for your resume',
      'Answer SQL & Python interview questions confidently',
      'Use GenAI to speed up analysis and documentation',
      'Eligible for Data Analyst & BI roles (6–12 LPA range)',
    ],
    whoFor: [
      'B.Tech, Degree & MCA graduates',
      'Career switchers with no coding background',
      'Anyone targeting analyst roles in IT services & product companies',
    ],
  },
  {
    slug: 'data-science-with-genai',
    icon: '🔬',
    title: 'Data Science with GenAI',
    color: 'from-purple-500/20 to-pink-500/10',
    accent: 'gh-purple',
    image: '/data_science_card_1781095310475.png',
    tagline: 'Master ML models, deep learning basics & AI-driven data science.',
    shortDesc: 'Build predictive models and deploy AI solutions with industry projects.',
    duration: '5–6 Months',
    level: 'Intermediate Track',
    mode: 'Classroom · KPHB, Hyderabad',
    description:
      'A comprehensive Data Science program covering statistics, machine learning, model evaluation, and GenAI integration. You will train models on real data, understand MLOps basics, and create a portfolio that stands out in Data Scientist interviews.',
    modules: [
      'Python, NumPy & Pandas for DS',
      'Statistics & exploratory data analysis',
      'Machine learning algorithms',
      'Model tuning, validation & deployment basics',
      'GenAI & LLMs for data science workflows',
      'End-to-end DS capstone + interview prep',
    ],
    skills: ['Machine Learning', 'Statistics', 'Feature Engineering', 'Model Evaluation', 'GenAI APIs'],
    tools: ['Python', 'Scikit-learn', 'Jupyter', 'Matplotlib', 'OpenAI APIs', 'Git'],
    outcomes: [
      'Ship ML projects with clear business impact stories',
      'Explain models and metrics in technical interviews',
      'Integrate LLMs into data pipelines and notebooks',
      'Target Data Scientist & ML Engineer entry roles',
    ],
    whoFor: [
      'Graduates with basic math/statistics interest',
      'Developers moving into data science',
      'Analysts upskilling to predictive modeling',
    ],
  },
  {
    slug: 'business-analyst-with-genai',
    icon: '📈',
    title: 'Business Analyst with GenAI',
    color: 'from-emerald-500/20 to-teal-500/10',
    accent: 'gh-green',
    image: '/business_analyst_card_1781095327176.png',
    tagline: 'Bridge business needs and technology with BA skills & GenAI.',
    shortDesc: 'Requirements, Agile, documentation & AI tools for modern BA roles.',
    duration: '4 Months',
    level: 'Beginner Friendly',
    mode: 'Classroom · KPHB, Hyderabad',
    description:
      'Learn how to gather requirements, write BRDs, work in Agile teams, and use Generative AI for documentation, user stories, and stakeholder communication. Ideal for graduates targeting Business Analyst roles in IT services and consulting firms.',
    modules: [
      'BA fundamentals & SDLC / Agile',
      'Requirement gathering & user stories',
      'BRD, FRD & process documentation',
      'SQL basics & data for business decisions',
      'GenAI for specs, emails & presentations',
      'BA case studies + mock client sessions',
    ],
    skills: ['Requirements Analysis', 'Agile / Scrum', 'Documentation', 'Stakeholder Communication', 'GenAI'],
    tools: ['Jira', 'Confluence', 'Excel', 'SQL Basics', 'ChatGPT', 'Miro / FigJam'],
    outcomes: [
      'Deliver BA artifacts used in real project simulations',
      'Communicate clearly with dev and business teams',
      'Use AI to draft and refine requirements faster',
      'Prepare for BA interviews at TCS, Accenture, Capgemini & more',
    ],
    whoFor: [
      'Non-coding graduates preferring business-facing IT roles',
      'Domain experts moving into IT business analysis',
      'Anyone with strong communication and problem-solving skills',
    ],
  },
  {
    slug: 'full-stack-ai-ml',
    icon: '🧠',
    title: 'Full Stack AI / ML',
    color: 'from-violet-500/20 to-indigo-500/10',
    accent: 'gh-purple',
    image: '/full_stack_ai_card_1781095343298.png',
    tagline: 'Build full-stack apps powered by machine learning & GenAI APIs.',
    shortDesc: 'Frontend, backend, APIs & deploy ML/GenAI features in production apps.',
    duration: '6 Months',
    level: 'Advanced Track',
    mode: 'Classroom · KPHB, Hyderabad',
    description:
      'Become a Full Stack AI engineer by combining web development, REST APIs, databases, and ML/GenAI integration. You will build applications that embed chatbots, recommendation logic, and model endpoints — exactly what product companies hire for today.',
    modules: [
      'Python & backend APIs (FastAPI / Flask)',
      'React / frontend integration basics',
      'Databases & authentication patterns',
      'ML model serving & GenAI API integration',
      'Docker & cloud deployment fundamentals',
      'Full-stack AI capstone project',
    ],
    skills: ['Full Stack Development', 'REST APIs', 'ML Integration', 'GenAI Apps', 'Deployment'],
    tools: ['Python', 'FastAPI', 'React', 'PostgreSQL', 'OpenAI APIs', 'Docker', 'Git'],
    outcomes: [
      'Deploy a live full-stack app with AI features',
      'Demonstrate end-to-end architecture in interviews',
      'Work independently on AI product features',
      'Qualify for Full Stack AI / ML Engineer roles',
    ],
    whoFor: [
      'Graduates serious about software + AI engineering',
      'Developers adding ML & GenAI to their stack',
      'Learners who enjoy building complete products',
    ],
  },
  {
    slug: 'full-stack-python-with-ai',
    icon: '🐍',
    title: 'Full Stack Python with AI',
    color: 'from-yellow-500/20 to-orange-500/10',
    accent: 'cyber-pink',
    image: '/full_stack_python_card_1781095357271.png',
    tagline: 'Python-first full stack path with modern AI tooling.',
    shortDesc: 'Django/Flask, databases, automation & AI agents from scratch.',
    duration: '5–6 Months',
    level: 'Beginner to Intermediate',
    mode: 'Classroom · KPHB, Hyderabad',
    description:
      'Start from Python basics and progress to building web applications, automations, and AI-powered features. This is our most popular track for graduates who want strong coding fundamentals plus GenAI skills for Python Developer and AI automation roles.',
    modules: [
      'Python programming from zero',
      'OOP, files, APIs & error handling',
      'Django / Flask web development',
      'Databases & ORM patterns',
      'AI automation, agents & scripting',
      'Portfolio projects + coding interview prep',
    ],
    skills: ['Python', 'Web Development', 'APIs', 'Automation', 'AI Agents', 'Git'],
    tools: ['Python', 'Django', 'Flask', 'SQLite / PostgreSQL', 'LangChain Basics', 'GitHub'],
    outcomes: [
      'Build 3+ Python projects for GitHub portfolio',
      'Solve coding rounds with structured practice',
      'Create automations and simple AI agents',
      'Target Python Developer & AI automation roles',
    ],
    whoFor: [
      'Complete beginners starting their coding journey',
      'Degree & B.Tech grads targeting developer roles',
      'Anyone who wants Python as their primary career skill',
    ],
  },
]

export function getCourseBySlug(slug) {
  return COURSE_DETAILS.find((course) => course.slug === slug)
}

export const COURSES = COURSE_DETAILS.map(({ icon, title, color, slug, shortDesc, image }) => ({
  icon,
  title,
  color,
  slug,
  shortDesc,
  image,
}))
